# Generated by Django 4.0 on 2022-09-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_patient_remove_person_city_remove_person_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
