# Generated by Django 4.0 on 2022-09-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_patient_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='patient',
        ),
    ]
