# Generated by Django 4.0 on 2022-09-19 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_registered_mail_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=2083)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.ManyToManyField(related_name='items', to='project.Category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ordered_time', models.DateTimeField(default=datetime.datetime.now)),
                ('items', models.ManyToManyField(blank=True, related_name='order', to='project.MenuItems')),
            ],
        ),
        migrations.DeleteModel(
            name='Registered_mail',
        ),
    ]
