# Generated by Django 4.1 on 2022-09-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_category_menuitems_orderitems_delete_registered_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
