# Generated by Django 4.0 on 2022-10-04 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItems',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='menu',
            new_name='product',
        ),
    ]
