# Generated by Django 4.0 on 2022-10-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0015_shippingaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='DeliveryAddress',
        ),
    ]
