# Generated by Django 4.1 on 2022-10-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_order_complete_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orders',
            field=models.ManyToManyField(null=True, to='project.order'),
        ),
    ]
